Added resource agents for neutron-lbaas and neutron-vpn

diff --git a/ocf/neutron-lbaas-agent b/ocf/neutron-lbaas-agent
--- a/ocf/neutron-lbaas-agent
+++ b/ocf/neutron-lbaas-agent
@@ -1,18 +1,15 @@
 #!/bin/sh
 #
 #
-# OpenStack DHCP Service (neutron-dhcp-agent)
+# OpenStack LBAAS Service (neutron-lbaas-agent)
 #
-# Description:  Manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource
+# Description:  Manages an OpenStack LBAAS Service (neutron-lbaas-agent) process as an HA resource
 #
-# Authors: Emilien Macchi
-# Mainly inspired by the Nova Network resource agent written by Emilien Macchi & Sebastien Han
+# Authors:      Marcio A. Silva
+# Mainly inspired by the Neutron L3 resource agent written by Emilien Macchi
 #
-# Support:      openstack@lists.launchpad.net
+# Support:      marcios@us.ibm.com
 # License:      Apache Software License (ASL) 2.0
-#
-# Small changes made by marcios@us.ibm.com to allow it be executed directly 
-# from a bash prompt.
 #
 # See usage() function below for more details ...
 #
@@ -34,9 +31,9 @@ OCF_ROOT=${OCF_ROOT:-/usr/lib/ocf}
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="neutron-dhcp-agent"
+OCF_RESKEY_binary_default="neutron-lbaas-agent"
 OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
-OCF_RESKEY_plugin_config_default="/etc/neutron/dhcp_agent.ini"
+OCF_RESKEY_plugin_config_default="/etc/neutron/lbaas_agent.ini"
 OCF_RESKEY_user_default="neutron"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_amqp_server_port_default="5672"
@@ -54,7 +51,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource 
+        $0 manages an OpenStack LBAAS Service (neutron-lbaas-agent) process as an HA resource 
 
         The 'start' operation starts the networking service.
         The 'stop' operation stops the networking service.
@@ -70,22 +67,22 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="neutron-dhcp-agent">
+<resource-agent name="neutron-lbaas-agent">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Neutron DHCP Service (neutron-dhcp-agent)
-May manage a neutron-dhcp-agent instance or a clone set that 
-creates a distributed neutron-dhcp-agent cluster.
+Resource agent for the OpenStack Neutron LBAAS Service (neutron-lbaas-agent)
+May manage a neutron-lbaas-agent instance or a clone set that 
+creates a distributed neutron-lbaas-agent cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack DHCP Service (neutron-dhcp-agent)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack LBAAS Service (neutron-lbaas-agent)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Server server binary (neutron-dhcp-agent)
+Location of the OpenStack LBAAS Server server binary (neutron-lbaas-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server server binary (neutron-dhcp-agent)</shortdesc>
+<shortdesc lang="en">OpenStack LBAAS Server server binary (neutron-lbaas-agent)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
@@ -93,31 +90,31 @@ Location of the OpenStack DHCP Server server binary (neutron-dhcp-agent)
 <longdesc lang="en">
 Location of the OpenStack Neutron Service (neutron-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (neutron-server) config file</shortdesc>
+<shortdesc lang="en">OpenStack LBAAS Server (neutron-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="plugin config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack DHCP Service (neutron-dhcp-agent) configuration file
+Location of the OpenStack LBAAS Service (neutron-lbaas-agent) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Server (neutron-dhcp-agent) config file</shortdesc>
+<shortdesc lang="en">OpenStack LBAAS Server (neutron-lbaas-agent) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_plugin_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack DHCP Service (neutron-dhcp-agent)
+User running OpenStack LBAAS Service (neutron-lbaas-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) user</shortdesc>
+<shortdesc lang="en">OpenStack LBAAS Service (neutron-lbaas-agent) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack DHCP Service (neutron-dhcp-agent) instance
+The pid file to use for this OpenStack LBAAS Service (neutron-lbaas-agent) instance
 </longdesc>
-<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) pid file</shortdesc>
+<shortdesc lang="en">OpenStack LBAAS Service (neutron-lbaas-agent) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>  
 
@@ -127,14 +124,13 @@ The listening port number of the AMQP server. Mandatory to perform a monitor che
 </longdesc>                                                                                                                                                                                                               
 <shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
 <content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
-</parameter>      
-
+</parameter>   
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack DHCP Service (neutron-dhcp-agent)
+Additional parameters to pass on to the OpenStack LBAAS Service (neutron-lbaas-agent)
 </longdesc>
-<shortdesc lang="en">Additional parameters for neutron-dhcp-agent</shortdesc>
+<shortdesc lang="en">Additional parameters for neutron-lbaas-agent</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -155,7 +151,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-neutron_dhcp_agent_validate() {
+neutron_lbaas_agent_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
@@ -181,12 +177,12 @@ neutron_dhcp_agent_validate() {
     true
 }
 
-neutron_dhcp_agent_status() {
+neutron_lbaas_agent_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) is not running"
+        ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -197,17 +193,17 @@ neutron_dhcp_agent_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack DHCP Server (neutron-dhcp-agent) is not running"
+        ocf_log info "Old PID file found, but OpenStack LBAAS Server (neutron-lbaas-agent) is not running"
         return $OCF_NOT_RUNNING
     fi
 }
 
-neutron_dhcp_agent_monitor() {
+neutron_lbaas_agent_monitor() {
     local rc
     local pid
     local network_amqp_check
     
-    neutron_dhcp_agent_status
+    neutron_lbaas_agent_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -216,61 +212,61 @@ neutron_dhcp_agent_monitor() {
     fi
 
     # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other Neutron process with the same connection behavior (for example neutron-server)
+    # We are sure to hit the lbaas-agent process and not other Neutron process with the same connection behavior (for example neutron-server)
         pid=`cat $OCF_RESKEY_pid`
         # check the connections according to the PID
         network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
         rc=$?
 	    if [ $rc -ne 0 ]; then
-	        ocf_log err "Neutron DHCP Server is not connected to the AMQP server : $rc"
+	        ocf_log err "Neutron LBAAS Server is not connected to the AMQP server : $rc"
 	        return $OCF_NOT_RUNNING
 	    fi
 
-    ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) monitor succeeded"
+    ocf_log debug "OpenStack LBAAS Server (neutron-lbaas-agent) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-neutron_dhcp_agent_start() {
+neutron_lbaas_agent_start() {
     local rc
 
-    neutron_dhcp_agent_status
+    neutron_lbaas_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already running"
+        ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual neutron-dhcp-agent daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual neutron-lbaas-agent daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
-       --config-file=$OCF_RESKEY_plugin_config --log-file=/var/log/neutron/dhcp-agent.log $OCF_RESKEY_additional_parameters"' >> \
+       --config-file=$OCF_RESKEY_plugin_config --log-file=/var/log/neutron/lbaas-agent.log $OCF_RESKEY_additional_parameters"' >> \
 	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    neutron_dhcp_agent_monitor
+    neutron_lbaas_agent_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) start failed"
+        ocf_log err "OpenStack LBAAS Server (neutron-lbaas-agent) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) started"
+    ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) started"
     return $OCF_SUCCESS
 }
 
-neutron_dhcp_agent_stop() {
+neutron_lbaas_agent_stop() {
     local rc
     local pid
 
-    neutron_dhcp_agent_status
+    neutron_lbaas_agent_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already stopped"
+        ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) already stopped"
         return $OCF_SUCCESS
     fi
 
@@ -280,7 +276,7 @@ neutron_dhcp_agent_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) couldn't be stopped"
+        ocf_log err "OpenStack LBAAS Server (neutron-lbaas-agent) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
@@ -291,26 +287,26 @@ neutron_dhcp_agent_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        neutron_dhcp_agent_status
+        neutron_lbaas_agent_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack LBAAS Server (neutron-lbaas-agent) still hasn't stopped yet. Waiting ..."
     done
 
-    neutron_dhcp_agent_status
+    neutron_lbaas_agent_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
 
-    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) stopped"
+    ocf_log info "OpenStack LBAAS Server (neutron-lbaas-agent) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -327,14 +323,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-neutron_dhcp_agent_validate || exit $?
+neutron_lbaas_agent_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        neutron_dhcp_agent_start;;
-  stop)         neutron_dhcp_agent_stop;;
-  status)       neutron_dhcp_agent_status;;
-  monitor)      neutron_dhcp_agent_monitor;;
+  start)        neutron_lbaas_agent_start;;
+  stop)         neutron_lbaas_agent_stop;;
+  status)       neutron_lbaas_agent_status;;
+  monitor)      neutron_lbaas_agent_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
diff --git a/ocf/neutron-vpn-agent b/ocf/neutron-vpn-agent
--- a/ocf/neutron-vpn-agent
+++ b/ocf/neutron-vpn-agent
@@ -1,27 +1,25 @@
 #!/bin/sh
 #
 #
-# OpenStack Neutron Metadata Agent (neutron-metadata-agent)
+# OpenStack VPN Service (neutron-vpn-agent)
 #
-# Description:  Manages an OpenStack Network Metadata Server (neutron-metadata-agent) process as an HA resource
+# Description:  Manages an OpenStack VPN Service (neutron-vpn-agent) process as an HA resource
 #
-# Authors:      Sebastien Han
-# Mainly inspired by the Glance API resource agent written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
+# Authors:      Marcio A. Silva
+# Mainly inspired by the Neutron L3 resource agent written by Emilien Macchi
 #
-# Support:      openstack@lists.launchpad.net
+# Support:      marcios@us.ibm.com
 # License:      Apache Software License (ASL) 2.0
-#
-# Small changes made by marcios@us.ibm.com to allow it be executed directly 
-# from a bash prompt.
 #
 # See usage() function below for more details ...
 #
 # OCF instance parameters:
 #   OCF_RESKEY_binary
 #   OCF_RESKEY_config
-#   OCF_RESKEY_agent_config
+#   OCF_RESKEY_l3_plugin_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
+#   OCF_RESKEY_amqp_server_port
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -33,17 +31,23 @@ OCF_ROOT=${OCF_ROOT:-/usr/lib/ocf}
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="neutron-metadata-agent"
+OCF_RESKEY_binary_default="neutron-vpn-agent"
 OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
-OCF_RESKEY_agent_config_default="/etc/neutron/metadata_agent.ini"
+OCF_RESKEY_l3_plugin_config_default="/etc/neutron/l3_agent.ini"
+OCF_RESKEY_vpn_plugin_config_default="/etc/neutron/vpn_agent.ini"
+OCF_RESKEY_fwaas_plugin_config_default="/etc/neutron/fwaas_agent.ini"
 OCF_RESKEY_user_default="neutron"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
+OCF_RESKEY_amqp_server_port_default="5672"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
-: ${OCF_RESKEY_agent_config=${OCF_RESKEY_agent_config_default}}
+: ${OCF_RESKEY_l3_plugin_config=${OCF_RESKEY_l3_plugin_config_default}}
+: ${OCF_RESKEY_vpn_plugin_config=${OCF_RESKEY_vpn_plugin_config_default}}
+: ${OCF_RESKEY_fwaas_plugin_config=${OCF_RESKEY_fwaas_plugin_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
+: ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}
 
 #######################################################################
 
@@ -51,14 +55,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Neutron Metadata Agent (neutron-metadata-agent) process as an HA resource
+        $0 manages an OpenStack VPN Service (neutron-vpn-agent) process as an HA resource 
 
-        The 'start' operation starts the metadata server service.
-        The 'stop' operation stops the metadata server service.
+        The 'start' operation starts the networking service.
+        The 'stop' operation stops the networking service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the metadata server service is running
-        The 'monitor' operation reports whether the metadata server service seems to be working
+        The 'status' operation reports whether the networking service is running
+        The 'monitor' operation reports whether the networking service seems to be working
 
 UEND
 }
@@ -67,56 +71,72 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="neutron-metadata-agent">
+<resource-agent name="neutron-vpn-agent">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Neutron Metadata Agent (neutron-metadata-agent)
-May manage a neutron-metadata-agent instance or a clone set that
-creates a distributed neutron-metadata-agent cluster.
+Resource agent for the OpenStack Neutron VPN Service (neutron-vpn-agent)
+May manage a neutron-vpn-agent instance or a clone set that 
+creates a distributed neutron-vpn-agent cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Neutron Metadata Agent (neutron-metadata-agent)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack VPN Service (neutron-vpn-agent)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Neutron Metadata Agent server binary (neutron-metadata-agent)
+Location of the OpenStack VPN Server server binary (neutron-vpn-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack Neutron Metadata Agent server binary (neutron-metadata-agent)</shortdesc>
+<shortdesc lang="en">OpenStack VPN Server server binary (neutron-vpn-agent)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Neutron Metadata Agent (neutron-metadata-agent) configuration file
+Location of the OpenStack Neutron Service (neutron-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Neutron Metadata Agent (neutron-metadata-agent) config file</shortdesc>
+<shortdesc lang="en">OpenStack VPN Server (neutron-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
+</parameter>
+
+<parameter name="l3 plugin config" unique="0" required="0">
+<longdesc lang="en">
+Location of the OpenStack VPN Service (neutron-vpn-agent) L3 plugin configuration file
+</longdesc>
+<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) L3 plugin config file</shortdesc>
+<content type="string" default="${OCF_RESKEY_l3_plugin_config_default}" />
+</parameter>
+
+<parameter name="vpn plugin config" unique="0" required="0">
+<longdesc lang="en">
+Location of the OpenStack VPN Service (neutron-vpn-agent) VPN plugin configuration file
+</longdesc>
+<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) VPN plugin config file</shortdesc>
+<content type="string" default="${OCF_RESKEY_vpn_plugin_config_default}" />
+</parameter>
+
+<parameter name="fwaas plugin config" unique="0" required="0">
+<longdesc lang="en">
+Location of the OpenStack VPN Service (neutron-vpn-agent) FWAAS plugin configuration file
+</longdesc>
+<shortdesc lang="en">OpenStack VPN Server (neutron-vpn-agent) FWAAS plugin config file</shortdesc>
+<content type="string" default="${OCF_RESKEY_fwaas_plugin_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Neutron Metadata Agent (neutron-metadata-agent)
+User running OpenStack VPN Service (neutron-vpn-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack Neutron Metadata Agent (neutron-metadata-agent) user</shortdesc>
+<shortdesc lang="en">OpenStack VPN Service (neutron-vpn-agent) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
-</parameter>
-
-<parameter name="agent_config" unique="0" required="0">
-<longdesc lang="en">
-Location of the OpenStack Metadata agent configuration file
-</longdesc>
-<shortdesc lang="en">OpenStack Metadata (neutron-metadata-agent) config file</shortdesc>
-<content type="string" default="${OCF_RESKEY_agent_config_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Neutron Metadata Agent (neutron-metadata-agent) instance
+The pid file to use for this OpenStack VPN Service (neutron-vpn-agent) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Neutron Metadata Agent (neutron-metadata-agent) pid file</shortdesc>
+<shortdesc lang="en">OpenStack VPN Service (neutron-vpn-agent) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
-</parameter>
+</parameter>  
 
 <parameter name="amqp_server_port" unique="0" required="0">                                                                                                                                                              
 <longdesc lang="en">                                                                                                                                                                                                      
@@ -124,24 +144,23 @@ The listening port number of the AMQP server. Mandatory to perform a monitor che
 </longdesc>                                                                                                                                                                                                               
 <shortdesc lang="en">AMQP listening port</shortdesc>                                                                                                                                                                      
 <content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
-</parameter>      
- 
+</parameter>
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Neutron Metadata Agent (neutron-metadata-agent)
+Additional parameters to pass on to the OpenStack VPN Service (neutron-vpn-agent)
 </longdesc>
-<shortdesc lang="en">Additional parameters for neutron-metadata-agent</shortdesc>
+<shortdesc lang="en">Additional parameters for neutron-vpn-agent</shortdesc>
 <content type="string" />
 </parameter>
 
 </parameters>
 
 <actions>
-<action name="start" timeout="10" />
-<action name="stop" timeout="10" />
-<action name="status" timeout="10" />
-<action name="monitor" timeout="5" interval="10" />
+<action name="start" timeout="20" />
+<action name="stop" timeout="20" />
+<action name="status" timeout="20" />
+<action name="monitor" timeout="30" interval="20" />
 <action name="validate-all" timeout="5" />
 <action name="meta-data" timeout="5" />
 </actions>
@@ -152,12 +171,12 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-neutron_metadata_agent_validate() {
+neutron_vpn_agent_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    
+
     # A config file on shared storage that is not available
     # during probes is OK.
     if [ ! -f $OCF_RESKEY_config ]; then
@@ -178,12 +197,12 @@ neutron_metadata_agent_validate() {
     true
 }
 
-neutron_metadata_agent_status() {
+neutron_vpn_agent_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) is not running"
+        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -194,74 +213,81 @@ neutron_metadata_agent_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Neutron Metadata Agent (neutron-metadata-agent) is not running"
+        ocf_log info "Old PID file found, but OpenStack VPN Server (neutron-vpn-agent) is not running"
         return $OCF_NOT_RUNNING
     fi
 }
 
-neutron_metadata_agent_monitor() {
+neutron_vpn_agent_monitor() {
+    local rc
     local pid
-    local rc
-
-    if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) is not running"
-        return $OCF_NOT_RUNNING
-    else
-        pid=`cat $OCF_RESKEY_pid`
-    fi
-
-    ocf_run -warn kill -s 0 $pid
+    local network_amqp_check
+    
+    neutron_vpn_agent_status
     rc=$?
-    if [ $rc -eq 0 ]; then
-        return $OCF_SUCCESS
-    else
-        ocf_log info "Old PID file found, but OpenStack Neutron Metadata Agent (neutron-metadata-agent) is not running"
-        return $OCF_NOT_RUNNING
+
+    # If status returned anything but success, return that immediately
+    if [ $rc -ne $OCF_SUCCESS ]; then
+        return $rc
     fi
+
+    # Check the connections according to the PID.
+    # We are sure to hit the vpn-agent process and not other Neutron process with the same connection behavior (for example neutron-server)
+        pid=`cat $OCF_RESKEY_pid`
+        # check the connections according to the PID
+        network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
+        rc=$?
+	    if [ $rc -ne 0 ]; then
+	        ocf_log err "Neutron VPN Server is not connected to the Neutron server: $rc"
+	        return $OCF_NOT_RUNNING
+	    fi
+
+    ocf_log debug "OpenStack VPN Server (neutron-vpn-agent) monitor succeeded"
+    return $OCF_SUCCESS
 }
 
-neutron_metadata_agent_start() {
+neutron_vpn_agent_start() {
     local rc
 
-    neutron_metadata_agent_status
+    neutron_vpn_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) already running"
+        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual neutron-server daemon with correct configurations files (server + plugin)
-    # Don't use ocf_run as we're sending the tool's output
+    # run the actual neutron-vpn-agent daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
-       	--config-file=$OCF_RESKEY_agent_config --log-file=/var/log/neutron/metadata.log $OCF_RESKEY_additional_parameters"' >> \
+       --config-file=$OCF_RESKEY_vpn_plugin_config --config-file=$OCF_RESKEY_l3_plugin_config \
+       --config-file=$OCF_RESKEY_fwaas_plugin_config --log-file=/var/log/neutron/vpn-agent.log $OCF_RESKEY_additional_parameters"' >> \
 	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    neutron_metadata_agent_monitor
+    neutron_vpn_agent_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Neutron Metadata Agent (neutron-metadata-agent) start failed"
+        ocf_log err "OpenStack VPN Server (neutron-vpn-agent) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) started"
+    ocf_log info "OpenStack VPN Server (neutron-vpn-agent) started"
     return $OCF_SUCCESS
 }
 
-neutron_metadata_agent_stop() {
+neutron_vpn_agent_stop() {
     local rc
     local pid
 
-    neutron_metadata_agent_status
+    neutron_vpn_agent_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) already stopped"
+        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) already stopped"
         return $OCF_SUCCESS
     fi
 
@@ -270,7 +296,7 @@ neutron_metadata_agent_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Neutron Metadata Agent (neutron-metadata-agent) couldn't be stopped"
+        ocf_log err "OpenStack VPN Server (neutron-vpn-agent) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
@@ -281,26 +307,26 @@ neutron_metadata_agent_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        neutron_metadata_agent_status
+        neutron_vpn_agent_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Neutron Metadata Agent (neutron-metadata-agent) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack VPN Server (neutron-vpn-agent) still hasn't stopped yet. Waiting ..."
     done
 
-    neutron_metadata_agent_status
+    neutron_vpn_agent_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack VPN Server (neutron-vpn-agent) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
 
-    ocf_log info "OpenStack Neutron Metadata Agent (neutron-metadata-agent) stopped"
+    ocf_log info "OpenStack VPN Server (neutron-vpn-agent) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -317,14 +343,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-neutron_metadata_agent_validate || exit $?
+neutron_vpn_agent_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        neutron_metadata_agent_start;;
-  stop)         neutron_metadata_agent_stop;;
-  status)       neutron_metadata_agent_status;;
-  monitor)      neutron_metadata_agent_monitor;;
+  start)        neutron_vpn_agent_start;;
+  stop)         neutron_vpn_agent_stop;;
+  status)       neutron_vpn_agent_status;;
+  monitor)      neutron_vpn_agent_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
